site_name: FairBench
site_author: Emmanouil (Manios) Krasanakis

nav:
    - Home: 'index.md'
    - 'quickstart.md'
    - Basics:
        - 'basics/forks.md'
        - 'basics/reports.md'
        - 'basics/interactive.md'
        - 'basics/modelcards.md'
    - Advanced:
        - 'advanced/metrics.md'
        - 'advanced/manipulation.md'
        - 'advanced/distributed.md'

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

theme:
  name: readthedocs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch

extra_css:
  - theme_extend.css