site_name: FairBench
site_author: Emmanouil (Manios) Krasanakis

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - attr_list
  - pymdownx.critic:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_png

plugins:
  - exclude:
      glob:
        - images/*

theme:
  name: readthedocs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch