site_name: FairBench
site_author: Emmanouil (Manios) Krasanakis

nav:
    - Home: 'index.md'
    - 'quickstart.md'
    - Basics:
        - 'basics/forks.md'
        - 'basics/reports.md'
        - 'basics/interactive.md'
        - 'basics/modelcards.md'
    - Advanced:
        - 'advanced/metrics.md'
        - 'advanced/ml_integration.md'
        - 'advanced/manipulation.md'
        - 'advanced/multimodal.md'

markdown_extensions:
  - admonition
  - mkautodoc
  - codehilite
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

theme:
  name: readthedocs
  logo: fairbench.png
  favicon: favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch

extra_css:
  - theme_extend.css

extra_javascript:
  - mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings
