site_name: FairBench
markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - attr_list

theme:
  name: readthedocs
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch